#!/usr/bin/python
# create html file from csv
# the filenames of csv and html are given during command execution
# python summary.py file-name.csv html-file.html [-p]
# -p is to denote that the summary should be generated by person, otherwise it is generated by questions

import sys
import csv
import shutil
import os
import stat
from os.path import basename, splitext
import time
from time import localtime, strftime
# Open the CSV file for reading
reader = csv.reader(open(sys.argv[1]))

# Create the HTML file for output
#htmlfile = open(sys.argv[2],"w")

file1 = open('error-file.txt', 'w')

log_file =''


#included_columns = [59] # column numbers of questions which should be included (excluding timestamp and email)
questions = {} 	# to store all the questions on the top row
name_col = 0 # to store the column number which contains name
flag= 0
# Extracts all the column numbers to be included in html.. Also extracts the column number of name (name_col)

image_path = 'H:\CATALOGUE 2013\Product Images high res'
colour_chart_path = 'H:\CATALOGUE 2013\Colour Charts high res'
logo_path = 'H:\CATALOGUE 2013\Logos High res'

global main_path
				
errorlist = []
global copied_flag

def get_logos():
	global flag
	global main_path
	global log_file	
	search_type = ''
	file_list = []

	if (flag == 0):
		search_type = 'colourchart'
		included_columns = 61
		print ("looking for colourcharts...")

	elif (flag ==1 ):
		search_type = 'logos'
		included_columns = 64
		print ("looking for logos...")
	elif (flag ==2):
		search_type = 'images'
		included_columns = 59
		print ("looking for images ... ")
		
	
	
	
	file_name = 'logfile-' + search_type + '-' + strftime("%Y%m%d-%H%M%S", localtime()) + '.txt'
	log_file = open(file_name, 'w')
	reader = csv.reader(open(sys.argv[1]))

	
	i =1 
	for row in reader:
		
		supplier_code = row[15]

		if (flag==0):
			save_path = main_path = '.\ColourChart'
			path = colour_chart_path
			save_path += '\\' + supplier_code + ' - ColourChart'

		elif (flag==1):
			save_path = main_path = '.\Logos'
			path = logo_path
			save_path += '\\' + supplier_code + ' - LOGO'
		elif (flag == 2):
			save_path = main_path = '.\Images'
			path = image_path
			save_path += '\\' + supplier_code + ' - Images'

		# Skip the top row which contains the column headings
		if (i==1):
			i = i +1
			continue
		
		# Get the names of the Persons
		#print row
		
		image_name = row[included_columns]
		#print (row[x])
		#print ("supplier: " + row[15])
		
		

		
		if not os.path.exists(save_path):
				os.makedirs(save_path)


		images_list = image_name.split(',')

		for item in images_list:
			try:
				copied_flag = 0
				item = splitext(item)[0]
				if (item in file_list or item =='' or item=='COLOUR CHART WITH THE DESIGNERS'):
					continue
				else:
					file_list.append(item)
					print ('searching for: ' + item)



				for dirName, subdirList, fileList in os.walk(path):
					if item in subdirList:
						
						save_dir =save_path+ '\\' + item

						print ('found directory: ' + os.path.join(dirName, item) )

						os.chmod(dirName+'\\'+item, stat.S_IWRITE)

						print ('copying directory: ' + os.path.join(dirName, item))

						shutil.copytree(os.path.join(dirName,item), save_dir)

						log_file.write('Directory Copied: ' + save_dir + '\n')
						copied_flag = 1
						continue
					
					#time.sleep(1)
					elif item not in fileList:
						continue


					for fname in fileList:
						#print ("image_name: " + image_name)
						fname_without_extension = splitext(fname)[0]
						
						#print ("found file: " + fname)
						
						#print ('jpt')
						#print (fname_without_extension)
						#print('image after: ' + image)
						
						if fname_without_extension == item:
							#print('inside')
							#print (os.path.join(dirName,fname))
							os.chmod(os.path.join(dirName, fname), stat.S_IWRITE)
							print('copying file : ' + fname )
							#print ('file list : ')
							#print (file_list)
							shutil.copy2(os.path.join(dirName, fname), save_path)
							log_file.write('File copied: ' + save_path + '\\' + fname +' \n')
							copied_flag = 1
				if copied_flag == 0:
					print ('Could not find file: ' + item)
					log_file.write('Could not find file: ' + item + '\n')
 				

			except Exception:
				global errorlist
				errorlist.append(item)
				log_file.write('Error copying : ' + item + '\n')
				print ('error copying: ' + item)






'''
def get_colourchart():
	
	global main_path
	
	file_list = []
	included_columns = [61]
	print ("looking for colourcharts...")

		
	for x in included_columns:
		
		reader = csv.reader(open(sys.argv[1]))

		
		i =1 
		for row in reader:
			
			supplier_code = row[15]
			save_path = main_path = '.\ColourChart'
			path = colour_chart_path
			save_path += '\\' + supplier_code + ' - ColourChart'

			# Skip the top row which contains the column headings
			if (i==1):
				i = i +1
				continue
			
			# Get the names of the Persons
			#print row
			
			image_name = row[x]
			#print (row[x])
			#print ("supplier: " + row[15])
			
			

			
			if not os.path.exists(save_path):
					os.makedirs(save_path)


			images_list = image_name.split(',')

			for image in images_list:
				try:
					image = splitext(image)[0]
					if (image in file_list):
						#print ('first')
						#print ('image before: ' + image)
						#time.sleep(2)
						continue
					else:
						#print (fname_without_extension)
						#print ('second')
						#print(file_list)
						file_list.append(image)


					if image == '' or image == 'COLOUR CHART WITH THE DESIGNERS':
						continue
					else:
						print ("Searching for: " + image)


					for dirName, subdirList, fileList in os.walk(path):
						if image in subdirList:
							
							save_path1 =save_path+ '\\' + image

							print ('found directory: ' + os.path.join(dirName, image) )

							os.chmod(dirName+'\\'+image, stat.S_IWRITE)
							shutil.copytree(os.path.join(dirName,image), save_path1)
							continue
						
						#time.sleep(1)

						for fname in fileList:
							#print ("image_name: " + image_name)


							#print ("found file: " + fname)
							fname_without_extension = splitext(fname)[0]
							#print ('jpt')
							#print (fname_without_extension)
							#print('image after: ' + image)
							#print ('fname: ' + fname)
							#print ('image: ' + image)
							if fname_without_extension == image:
								#print('inside')
								#print (os.path.join(dirName,fname))
								os.chmod(os.path.join(dirName, fname), stat.S_IWRITE)
								print('copying file : ' + image )
								#print ('file list : ')
								#print (file_list)
								shutil.copy2(os.path.join(dirName, fname), save_path)
		 				

				except Exception:
					global errorlist
					errorlist.append(image)
					print ('error copying: ' + image)
	
	




'''

def removeEmptyFolders(path):
  global log_file
  if not os.path.isdir(path):
    
    return

  # remove empty subfolders
  files = os.listdir(path)
  if len(files):
    for f in files:
      fullpath = os.path.join(path, f)
      if os.path.isdir(fullpath):
        removeEmptyFolders(fullpath)

  # if folder empty, delete it
  files = os.listdir(path)
  if len(files) == 0:
    print ("Removing empty folder:", path)
    log_file.write("Removing empty folder:" + path + '\n')
    os.rmdir(path)



			
if (len(sys.argv) == 3):
	if (sys.argv[2].lower() == '-c'):
		flag = 0
		
	elif (sys.argv[2].lower() == '-l'):
		flag = 1
	elif (sys.argv[2].lower() == '-i'):
		flag = 2
	else:
		print ("please supply valid argument '-i' , '-c', or '-l'")
		exit(1)

	get_logos()

	removeEmptyFolders(main_path)

	str1 = ''.join(errorlist)
	file1.write(str1)
	exit(0)

else:
	print ("please supply additional argument '-i', '-c', '-l'")
	exit(1)
#print (main_path)






		


    	

